"""add_hired_at_to_applications

Revision ID: 040c7235a290
Revises: 3d92684d2dc9
Create Date: 2025-12-03 14:20:37.215877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040c7235a290'
down_revision: Union[str, Sequence[str], None] = '3d92684d2dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'hired_at')
    # ### end Alembic commands ###
