"""Add_departments_and_job_status

Revision ID: 3d92684d2dc9
Revises: bb8e38f3ea2f
Create Date: 2025-11-30 11:20:38.294596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d92684d2dc9'
down_revision: Union[str, Sequence[str], None] = 'bb8e38f3ea2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('departments', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    op.drop_column('companies', 'departments')
    # ### end Alembic commands ###
