"""Add user status and feature flags

Revision ID: 3e5ad0e93fee
Revises: d6b60faff82b
Create Date: 2025-12-13 18:42:23.922416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5ad0e93fee'
down_revision: Union[str, Sequence[str], None] = 'd6b60faff82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE users SET status = 'active'")
    op.alter_column('users', 'status', nullable=False)
    op.add_column('users', sa.Column('feature_flags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feature_flags')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
