"""add_sso_fields

Revision ID: 4cf5c7a30ab5
Revises: c2a6545f5e4b
Create Date: 2025-11-27 17:17:34.098171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf5c7a30ab5'
down_revision: Union[str, Sequence[str], None] = 'c2a6545f5e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
