"""remove_system_logs

Revision ID: 65e09fffe628
Revises: 3b5f7a8c9d2e
Create Date: 2025-12-21 22:41:52.539663

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '65e09fffe628'
down_revision: Union[str, Sequence[str], None] = '3b5f7a8c9d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: system_logs table never existed in the main database migration chain.
    # It was intended for a separate logs database.
    # Making this a no-op to prevent errors when running migrations on a clean DB.
    pass
    # op.drop_index(op.f('idx_system_logs_component_created'), table_name='system_logs')
    # op.drop_index(op.f('idx_system_logs_errors'), table_name='system_logs', postgresql_where='(error_type IS NOT NULL)')
    # op.drop_index(op.f('idx_system_logs_level_created'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_company_id'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_component'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_deployment_environment'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_deployment_version'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_http_path'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_session_id'), table_name='system_logs')
    # op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    # op.drop_table('system_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Since upgrade was a no-op, downgrade must also be a no-op
    # to avoid creating a table that shouldn't exist in this DB.
    pass
    # op.create_table('system_logs',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('component', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('http_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('http_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('http_status', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('error_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('extra_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('deployment_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('deployment_environment', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('system_logs_company_id_fkey')),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('system_logs_user_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('system_logs_pkey'))
    # )
    # op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    # op.create_index(op.f('ix_system_logs_session_id'), 'system_logs', ['session_id'], unique=False)
    # op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    # op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    # op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    # op.create_index(op.f('ix_system_logs_http_path'), 'system_logs', ['http_path'], unique=False)
    # op.create_index(op.f('ix_system_logs_deployment_version'), 'system_logs', ['deployment_version'], unique=False)
    # op.create_index(op.f('ix_system_logs_deployment_environment'), 'system_logs', ['deployment_environment'], unique=False)
    # op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    # op.create_index(op.f('ix_system_logs_component'), 'system_logs', ['component'], unique=False)
    # op.create_index(op.f('ix_system_logs_company_id'), 'system_logs', ['company_id'], unique=False)
    # op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    # op.create_index(op.f('idx_system_logs_level_created'), 'system_logs', ['level', sa.literal_column('created_at DESC')], unique=False)
    # op.create_index(op.f('idx_system_logs_errors'), 'system_logs', ['error_type', 'created_at'], unique=False, postgresql_where='(error_type IS NOT NULL)')
    # op.create_index(op.f('idx_system_logs_component_created'), 'system_logs', ['component', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###