"""Add Summary

Revision ID: 8ff4227ce259
Revises: a6aa68ef9a17
Create Date: 2025-11-22 23:25:12.320797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff4227ce259'
down_revision: Union[str, Sequence[str], None] = 'a6aa68ef9a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_cvs', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_cvs', 'summary')
    # ### end Alembic commands ###
