"""Add SystemLog and UserInvitation models

Revision ID: ccb0d9fd7e5b
Revises: b731bf4fc640
Create Date: 2025-12-21 13:30:05.654760

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ccb0d9fd7e5b'
down_revision: Union[str, Sequence[str], None] = 'b731bf4fc640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
