"""add assigned_by and source to application

Revision ID: d6b60faff82b
Revises: ed2a676a8927
Create Date: 2025-12-13 17:20:41.159396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b60faff82b'
down_revision: Union[str, Sequence[str], None] = 'ed2a676a8927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('source', sa.String(), nullable=True))
    op.create_foreign_key(None, 'applications', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'source')
    op.drop_column('applications', 'assigned_by')
    # ### end Alembic commands ###
