"""Add settings to Company

Revision ID: dc4d379e050b
Revises: 65e09fffe628
Create Date: 2025-12-25 15:17:22.082468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc4d379e050b'
down_revision: Union[str, Sequence[str], None] = '65e09fffe628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_company_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_component'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_deployment_environment'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_deployment_version'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_http_path'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_session_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.add_column('companies', sa.Column('settings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'settings')
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('http_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('http_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('http_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deployment_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deployment_environment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('system_logs_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('system_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_logs_pkey'))
    )
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_system_logs_session_id'), 'system_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_http_path'), 'system_logs', ['http_path'], unique=False)
    op.create_index(op.f('ix_system_logs_deployment_version'), 'system_logs', ['deployment_version'], unique=False)
    op.create_index(op.f('ix_system_logs_deployment_environment'), 'system_logs', ['deployment_environment'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_component'), 'system_logs', ['component'], unique=False)
    op.create_index(op.f('ix_system_logs_company_id'), 'system_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    # ### end Alembic commands ###
