"""add_interview_outcome

Revision ID: e7d9a4c4dad0
Revises: c64808ba59a0
Create Date: 2025-11-27 18:23:46.454310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d9a4c4dad0'
down_revision: Union[str, Sequence[str], None] = 'c64808ba59a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('outcome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'outcome')
    # ### end Alembic commands ###
