"""add audit fields created_by modified_by

Revision ID: ed2a676a8927
Revises: ebe80c294a16
Create Date: 2025-12-13 17:05:53.194742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2a676a8927'
down_revision: Union[str, Sequence[str], None] = 'ebe80c294a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cvs', 'users', ['uploaded_by'], ['id'])
    op.add_column('departments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'departments', 'users', ['modified_by'], ['id'])
    op.add_column('jobs', sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jobs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'jobs', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'modified_by')
    op.drop_column('jobs', 'created_by')
    op.drop_column('jobs', 'modified_at')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'modified_by')
    op.drop_column('departments', 'created_by')
    op.drop_constraint(None, 'cvs', type_='foreignkey')
    op.drop_column('cvs', 'uploaded_by')
    # ### end Alembic commands ###
